server:
  port: 2333
  address: 0.0.0.0

plugins:
  lavalyrics:
    sources:
      - spotify
      - youtube
      - deezer
      - yandexMusic

  youtube:
    enabled: true
    clients: ["MUSIC", "WEB", "MWEB", "WEBEMBEDDED", "ANDROID_MUSIC"]
  lavasrc:
    providers:
      - 'ytsearch:"%ISRC%"'
      - "ytsearch:%QUERY%"
    sources:
      spotify: true
      applemusic: false
      deezer: false
      yandexmusic: false
      flowerytts: false
      youtube: true
    lyrics-sources:
      spotify: true
      youtube: true
    spotify:
      clientId: ${SPOTIFY_CLIENT_ID}
      clientSecret: ${SPOTIFY_CLIENT_SECRET}
      spDc: ${SPDC}
      countryCode: "IN"
      preferAnonymousToken: true
      customTokenEndpoint: "http://spotify-tokener:8080/api/token"
      playlistLoadLimit: 6
      albumLoadLimit: 6

lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:dbda8e7"
      snapshot: true
    - dependency: "com.github.topi314.lavasearch:lavasearch-plugin:1.0.0"
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.5"
    - dependency: "com.github.topi314.lavalyrics:lavalyrics-plugin:1.1.0"
  pluginsDir: "./plugins"
  server:
    password: ${LAVALINK_PASSWORD}
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    timeouts:
      connectTimeoutMs: 5000
      connectionRequestTimeoutMs: 5000
      socketTimeoutMs: 15000

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: DEBUG
    lavalink.server.io.RequestLoggingFilter: OFF
  request:
    enabled: true
    includeClientInfo: true
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000
  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
