name: Rebuild and Restart Bot on Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    environment: main
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    defaults:
      run:
        working-directory: /home/pratik2296/docker/discord

    steps:
      - name: Pull latest code
        run: |
          cd 2296-bot
          git pull origin main

      - name: Restart bot container
        run: |
          docker compose build bot
          docker compose up -d bot

      - name: Send Discord Notification
        run: |
          cd 2296-bot
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          COMMIT_HASH=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          curl -H "Content-Type: application/json" \
            -X POST "$DISCORD_WEBHOOK_URL" \
            -d @- <<EOF
          {
            "embeds": [{
              "title": "Bot has been restarted",
              "color": 3066993,
              "fields": [
                {
                  "name": "Repository",
                  "value": "2296-bot"
                },
                {
                  "name": "Commit",
                  "value": "\`$COMMIT_HASH\` - $COMMIT_MSG"
                },
                {
                  "name": "Author",
                  "value": "$COMMIT_AUTHOR",
                  "inline": true
                },
                {
                  "name": "Deployed At",
                  "value": "$TIMESTAMP",
                  "inline": true
                }
              ]
            }]
          }
          EOF
