name: Rebuild and Restart Bot on Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd ~/Desktop/2296-bot-docker/2296-bot
          git pull origin main

      - name: Restart docker
        run: |
          cd ~/Desktop/2296-bot-docker
          docker compose build discord-bot
          docker compose up -d discord-bot

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          curl -H "Content-Type: application/json" \
            -X POST "$DISCORD_WEBHOOK_URL" \
            -d '{
              "embeds": [{
                "title": "🤖 Bot Redeployed",
                "description": "'"$COMMIT_MSG"'",
                "color": 3066993
              }]
            }'